REVOKE ALL ON public.user_roles, public.profiles, public.products, public.cart_items, public.orders, public.order_items, public.order_status_history, public.inventory_changes FROM anon, authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT ON public.profiles TO authenticated;
GRANT UPDATE (full_name, phone, address, updated_at) ON public.profiles TO authenticated;
GRANT SELECT ON public.products TO anon, authenticated;
GRANT INSERT (title,style,fabric,color,pattern,occasion,description,price_paise,status,image_key,image_url) ON public.products TO authenticated;
GRANT UPDATE (title,style,fabric,color,pattern,occasion,description,price_paise,status,image_key,image_url,updated_at) ON public.products TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cart_items TO authenticated;
GRANT SELECT ON public.orders, public.order_items, public.order_status_history, public.inventory_changes TO authenticated;
REVOKE ALL ON SEQUENCE public.order_items_id_seq, public.order_status_history_id_seq, public.inventory_changes_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.products_id_seq FROM anon;
GRANT USAGE ON SEQUENCE public.products_id_seq TO authenticated;